create sequence adress_seq start with 1 increment by 50;
create sequence category_seq start with 1 increment by 50;
create sequence city_seq start with 1 increment by 50;
create sequence client_seq start with 1 increment by 50;
create sequence product_seq start with 1 increment by 50;
create sequence request_seq start with 1 increment by 50;
create table adress (id integer not null, bairro varchar(255), cep varchar(255), complemento varchar(255), logradouro varchar(255), numero varchar(255), city_id integer, client_id integer, primary key (id));
create table category (id integer not null, name varchar(255), primary key (id));
create table city (id integer not null, name varchar(255), state_id integer, primary key (id));
create table client (id integer not null, cpf_ou_cnpj varchar(255), client_type integer, email varchar(255), name varchar(255), primary key (id));
create table item_request (desconto float(53), preco float(53), quantidade integer, product_id integer not null, request_id integer not null, primary key (product_id, request_id));
create table payment (request_id integer not null, payment_type integer, primary key (request_id));
create table payment_with_bill (data_pagamento timestamp(6), data_vencimento timestamp(6), request_id integer not null, primary key (request_id));
create table payment_with_card (numero_de_parcelas integer, request_id integer not null, primary key (request_id));
create table product (id integer not null, name varchar(255), price float(53), primary key (id));
create table product_category (product_id integer not null, category_id integer not null);
create table request (id integer not null, instant timestamp(6), adress_delivery_id integer, client_id integer, primary key (id));
create table state (id  serial not null, name varchar(255), primary key (id));
create table telephone (client_id integer not null, telefones varchar(255));
alter table if exists client add constraint UK_bfgjs3fem0hmjhvih80158x29 unique (email);
alter table if exists adress add constraint FK1wxre6ktmrkjaa9qqy3y9m18o foreign key (city_id) references city;
alter table if exists adress add constraint FKomym9vx21lhnj061wrysjynts foreign key (client_id) references client;
alter table if exists city add constraint FK6p2u50v8fg2y0js6djc6xanit foreign key (state_id) references state;
alter table if exists item_request add constraint FK2q9x616akbtun5lwn6y8ci2oa foreign key (product_id) references product;
alter table if exists item_request add constraint FKe4qm9bo2qg2jp631mcgjka5ic foreign key (request_id) references request;
alter table if exists payment add constraint FK5pgyup82pk40rm2mo6jeqrbi7 foreign key (request_id) references request;
alter table if exists payment_with_bill add constraint FK3mn79hx1qnkj0eaaa3x1c1c8t foreign key (request_id) references payment;
alter table if exists payment_with_card add constraint FK7u0tjgmt9hpndyuro6tsdpjoj foreign key (request_id) references payment;
alter table if exists product_category add constraint FKkud35ls1d40wpjb5htpp14q4e foreign key (category_id) references category;
alter table if exists product_category add constraint FK2k3smhbruedlcrvu6clued06x foreign key (product_id) references product;
alter table if exists request add constraint FKqhtcya31xw3kv5v845wpv6849 foreign key (adress_delivery_id) references adress;
alter table if exists request add constraint FKdayt1j0e3kc0j52bn9b78dav foreign key (client_id) references client;
alter table if exists telephone add constraint FKt5031pgl80oxyxpp7cfgssrr9 foreign key (client_id) references client;
